// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/girivalam/BeyondArunachala.tsx": () => import("../components/mockups/girivalam/BeyondArunachala.tsx"),
  "./components/mockups/girivalam/EdgePanel.tsx": () => import("../components/mockups/girivalam/EdgePanel.tsx"),
  "./components/mockups/girivalam/TrackingScreen.tsx": () => import("../components/mockups/girivalam/TrackingScreen.tsx"),
  "./components/mockups/walk-flow/AfterScreen.tsx": () => import("../components/mockups/walk-flow/AfterScreen.tsx"),
  "./components/mockups/walk-flow/BeforeScreen.tsx": () => import("../components/mockups/walk-flow/BeforeScreen.tsx"),
  "./components/mockups/walk-flow/DuringScreen.tsx": () => import("../components/mockups/walk-flow/DuringScreen.tsx"),
  "./components/mockups/girivalam/memory/AtBanner.tsx": () => import("../components/mockups/girivalam/memory/AtBanner.tsx"),
  "./components/mockups/girivalam/memory/FarBanner.tsx": () => import("../components/mockups/girivalam/memory/FarBanner.tsx"),
  "./components/mockups/girivalam/memory/NearBanner.tsx": () => import("../components/mockups/girivalam/memory/NearBanner.tsx"),
  "./components/mockups/girivalam/memory/Timeline.tsx": () => import("../components/mockups/girivalam/memory/Timeline.tsx")
};
