// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/girivalam/BeyondArunachala.tsx": () => import("../components/mockups/girivalam/BeyondArunachala.tsx"),
  "./components/mockups/walk-flow/AfterScreen.tsx": () => import("../components/mockups/walk-flow/AfterScreen.tsx"),
  "./components/mockups/walk-flow/BeforeScreen.tsx": () => import("../components/mockups/walk-flow/BeforeScreen.tsx"),
  "./components/mockups/walk-flow/DuringScreen.tsx": () => import("../components/mockups/walk-flow/DuringScreen.tsx")
};
